### ISSUE TITLE
pix2pixHD or vid2vid

### ISSUE THREAD

**Issue by ghost** [acvictor/Obama-Lip-Sync#5]
possible to get better results with pix2pixHD or vid2vid https://github.com/NVIDIA/pix2pixHD or https://github.com/NVIDIA/vid2vid

**Comment by craftfortress** [comment]
Is this a question or a statement?

**Comment by cbsudux** [comment]
Hey! I'm considering reimplementing this with pix2pixHD. Have any of you given it a shot?

**Comment by acvictor** [comment]
No but you should! Would definitely help with odd border pixelation.
