### ISSUE TITLE
Bad shape input

### ISSUE THREAD

**Issue by eliranmoyal** [acvictor/Obama-Lip-Sync#6]
trying to run the example (after downloading all the relevant data) and getting this error:
```
ValueError: Error when checking input: expected lstm_1_input to have shape (50, 39) but got array with shape (10L, 39L)
```
Those where the log on output before the exception:
```
data/sampleAudio.wav
16000
('Shapes:', (5201L, 10L, 39L))
('Shapes:', (52010L, 39L))
```

**Comment by acvictor** [comment]
I think it's an issue with the look back value. Line 27 in run.py hardcodes the value to 50. Change this to 10 and it should work. I've missed setting its value from the argument parser, will fix this.
